apiVersion: v2
version: 0.1.0

name: knowledge-interface
type: application
description: A Helm chart for deploying the Cellebris Knowledge Center Interface.
home: https://github.com/cellebris/charts

dependencies:
    - name: zimagi-lib
      repository: https://charts.zimagi.com
      version: 0.1.6

maintainers:
    - email: adrian@cellebris.com
      name: adrianwebb
      url: https://github.com/adrianwebb
